---
- hosts: all
  become: true
  tasks:
    - name: Install the required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 86400
      with_items:
        - curl
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
        - cmake
        - gcc
        - binutils-dev
        - build-essential
        - python-pip
        - python-pyasn1
        - git
        - cmake
        - libbfd-dev
        - libiberty-dev

    - name: Install pip dependencies
      pip:
        name: "{{ item }}"
      with_items:
        - ndg-httpsclient

    - name: Download rust install
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/install-rust.sh

    - name: Install rust
      command: bash /tmp/install-rust.sh -y --default-toolchain nightly
      args:
        creates: /root/.cargo/bin/rustc

    - name: Get kcov
      git:
        repo: https://github.com/SimonKagstrom/kcov
        dest: /tmp/kcov
        version: v33

    - name: Create build dir
      file:
        path: /tmp/kcov/build
        state: directory

    - name: Build kcov
      command: cmake ..
      args:
        chdir: /tmp/kcov/build
        creates: /tmp/kcov/build/Makefile
    
    - name: Compile kcov
      command: make
      args:
        chdir: /tmp/kcov/build
        creates: /tmp/kcov/build/src/kcov
    
    - name: Install kcov
      command: make install
      args:
        chdir: /tmp/kcov/build
        creates: /usr/local/bin/kcov
